language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO="Django<1.5"
  - DJANGO="Django<1.6"
  - DJANGO="Django<1.7"
  - DJANGO="Django<1.8"

install:
  - pip install $DJANGO

before_script:
  - sh -c "if [ '$DJANGO' = 'Django<1.6' ]; then pip install django-discover-runner; fi"

script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO="Django<1.5.10"
      python: "3.3"
    - env: DJANGO="Django<1.5.10"
      python: "3.4"
