language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO=Django==1.4.15
  - DJANGO=Django==1.5.10
  - DJANGO=Django==1.6.7
  - DJANGO=Django==1.7.1

install:
  - pip install $DJANGO --use-mirrors

before_script:
  - sh -c "if [ '$DJANGO' = 'Django==1.5.10' ]; then pip install django-discover-runner; fi"

script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO=Django==1.5.10
      python: "3.4"
